### ISSUE TITLE
Traefik RP Doku Leads to 403

### ISSUE THREAD

**Issue by h1dden-da3m0n** [jellyfin/jellyfin-docs#117]
### Describe the bug
Okay, if you follow the instructions found un the official Docu for [Reverse Proxys](https://jellyfin.readthedocs.io/en/latest/administrator-docs/reverse-proxy/#traefik-with-docker-compose) for Traefik all you get once done is an https upgraded 403 response.
**Side note:** My setup uses a self signed cert for LAN access (yes, I have Jellyfin behind a Proxy for my LAN only with now remote sharing. pls don't judge me 😟 )

### To Reproduce

1. Setup the required docker container as shown in the [Reverse Proxys](https://jellyfin.readthedocs.io/en/latest/administrator-docs/reverse-proxy/#traefik-with-docker-compose) section to Traefik
2. try to access Jellyfin
3. profit?

**alternative (that yields the same result without RP)**
1. simply run `docker run
-p 8096:8096
-v jellyfin_config:/config
-v /host/media:/media
jellyfin/jellyfin:10.3.7`
2. try access Jellyfin
3. get greeted by a 403 Forbidden page :-(

### Expected behaviour
Setup the docker-compose files and toml file as shown by the docu => allows the user to access jellyfin

### Screenshots
![jellyfin](https://user-images.githubusercontent.com/33120068/64900189-01bf0f80-d67f-11e9-91b7-96ce7d9b4cca.png)
![traefik](https://user-images.githubusercontent.com/33120068/64900194-0b487780-d67f-11e9-9a33-c255a6fce7f4.png)

### Config- / Compose-Files
**Traefik**
```yaml
version: '3.7'

services:
  traefik:
    image: traefik:alpine
    command: --web --docker --docker.domain="local.lan" --logLevel="INFO"
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    volumes:
      - ./certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    restart: unless-stopped
    labels:
      - "traefik.frontend.rule=Host:traefik.local.lan"
      - "traefik.port=8080"
      - "traefik.backend=Traefik-Admin"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=86400"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"

networks:
  traefik:
    external: true
```

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[docker]
domain = "local.lan"
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
    ]
    [[entryPoints.https.tls.certificates]]
    certFile = "/certs/local_lan_wildcard.crt"
    keyFile  = "/certs/local_lan_wildcard.key"
```

**Jellyfin**
```yaml
version: '3.7'
services:
  jellyfin:
    image: jellyfin/jellyfin:10.3.7
    environment:
      - TZ=Europe/Vienna
    expose:
      - 8096
    labels:
      - "traefik.frontend.rule=Host:jellyfin.local.lan"
      - "traefik.port=8096"
      - "traefik.backend=JellyFin"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=86400"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
    volumes:
      - type: volume
        source: jellyfin_config
        target: /config
      - type: volume
        source: jellyfin_cache
        target: /cache
      - type: bind
        source: /mnt/nfs_media
        target: /media
    restart: unless-stopped
    networks:
      - traefik

volumes:
  jellyfin_config:
    external: true
  jellyfin_cache:
    external: true

networks:
  traefik:
    external: true
```

### System (please complete the following information):
 - OS: Docker
 - Browser: Firefox, (+ extra tests in Edge, I only have FF installed sry)
 - Jellyfin Version: 10.3.7
 - Reverse proxy: Traefik

### Additional context
This Issue seems to be related to [jellyfin#255](https://github.com/jellyfin/jellyfin/issues/255), yet not really as it seems to be a bit of a different behaviour.

Should I have opened this issue in the wrong repo then I'm terribly sorry, same goes for the case if this whole issue is only limited to my setup and me missing something

**Final Note** I’m sure it is not Traefiks fault, since I use it as a reverse proxy for Portainer and have no problems there 🤔 
For Jellyfin I'll change back to using `network_mode: "host"` and life with just *http* for the meantime ☹️

**Comment by PrplHaz4** [comment]
@h1dden-da3mon I added the bridge network (in your case "traefik") to the jf container (in addition to host) to get traefik working.

This makes sense because bridge networks purposely do not have access to the host network where the jf port is exposed.

**Comment by h1dden-da3m0n** [comment]
@PrplHaz4 Thank you for your quick response! 👍 
So, if I understand your comment right you did something like this?
```yaml
version: '3.7'
services:
  jellyfin:
    image: jellyfin/jellyfin:10.3.7
    environment:
      - TZ=Europe/Vienna
#    network_mode: "host"
    expose:
      - 8096
    labels:
      - "traefik.frontend.rule=Host:jellyfin.local.lan"
      - "traefik.port=8096"
      - "traefik.backend=JellyFin"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=86400"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
    volumes:
      - type: volume
        source: jellyfin_config
        target: /config
      - type: volume
        source: jellyfin_cache
        target: /cache
      - type: bind
        source: /mnt/nfs_media
        target: /media
    restart: unless-stopped
    networks:
      - traefik
      - hostnet

volumes:
  jellyfin_config:
    external: true
  jellyfin_cache:
    external: true

networks:
  traefik:
    external: true
  hostnet:
    external:
      name: host
```
(*note:* the `hostnet` is directly out of the docker-compose [references](https://docs.docker.com/compose/compose-file/#network-configuration-reference))

But as far as I can say / test this will end up in an compose error at start-up.
If you could be so kind as to share your docker-compose config, it would be much appreciated.

Besides that, any idea why a simple `docker run -p 8096:8096 -v jellyfin_config:/config -v /host/media:/media jellyfin/jellyfin:10.3.7` will also lead to a 403?
This has nothing to do with the RP and the only known issue related to only port sharing jellyfin is the issue I linked above (related to DLNA, not the concern of this issue)

pps.: Huge **THANK YOU** to the Jellyfin Devs and their community for this Project, after the Emby GPL fiasco (ppl that don't understand the GPL 😞 ) you did the only right thing and Forked away with at least a part of their Community, those who chose Emby over Plex because FOSS, and gained new users for being the NEW FOSS Media server 👍  and the 🍰 goes to you!
