### ISSUE TITLE
HWA with Nvidia GPUs + docker

### ISSUE THREAD

**Issue by D34DC3N73R** [jellyfin/jellyfin-docs#273]
I see a couple of issues with the documentation in regards to docker + hwa + nvidia gpus.

1.  Nvidia GPUs are supported when using docker-compose.
Prerequisites: nvidia drivers, nvidia docker 2 package, edited `/etc/docker/daemon.json` to make nvidia the default runtime in docker-compose v3+ (as you have outlined). Simply add the nvidia environment variables to the docker-compose jellyfin service.
```
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      ...
```
This should be compatible with any glibc distribution (which is required for nvidia drivers and nvidia docker 2).

2. When using docker v19.03+ (docker run), there is no reason to edit `/etc/docker/daemon.json` as gpu options have been integrated into the default runtime. The nvidia docker 2 package is no longer needed, but [nvidia container toolkit](https://github.com/NVIDIA/nvidia-docker) is required as well as nvidia drivers. You no longer need the specific nvidia environment variables or switching to the nvidia runtime. Just use  `--gpus all`
```
docker run -d \
--name=jellyfin \
--gpus all \
-p 8096:8096 \
-p 8920:8920 \
-v /config:/config \
-v /media:/media \
-v /cache:/cache \
--restart unless-stopped \
jellyfin/jellyfin
```
Again, this should be compatible with any glibc distribution (which is required for nvidia drivers and nvidia container toolkit).

**Comment by Artiume** [comment]
Would you be willing to get a working config using `user: 1000:1000` and `group_add: videogroup` I know of group 44 and 107 and had issues getting both groups added to the container. It's been hard getting the permissions right

**Comment by D34DC3N73R** [comment]
When using nvidia container toolkit / nvidia docker 2, you do not need to specify or add an alternate video group. This is from my docker-compose.yml. PUID/PGID .env is set to admin:admin (1000). 
```
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - $HOME/.config/jellyfin:/config
      - /mnt/media:/media
      - /dev/shm:/transcode
    ports:
      - 8095:8096
    restart: unless-stopped
```
Basically, the only time you need to specify or add the video group to your user is when you're passing /dev/dri (like you would if you wanted to use intel quick sync).

**Comment by Artiume** [comment]
```
environment:
 - PUID=$PUID
 - PGID=$PGID 
```
While I love the lsio image, these aren't compatible with our image lol. So you haven't had issues with setting the user with our image?

**Comment by D34DC3N73R** [comment]
nvenc works with your image as well
```
  jellyfin-test:
    image: jellyfin/jellyfin
    container_name: jellyfin-test
    user: 1000:1000
    environment:
      - TZ=$TZ
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - $HOME/.config/jellyfin-test:/config
      - /mnt/media:/media
      - /dev/shm:/transcode
    ports:
      - 8094:8096
```

Here's a snippet from the transcode log.
```
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (ac3 (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[hls @ 0x563227fce900] Opening '/transcode/6f1672a3fae3e09591d608543fa5a32c0.ts' for writing
Output #0, hls, to '/transcode/6f1672a3fae3e09591d608543fa5a32c.m3u8':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (h264_nvenc) (High), yuv420p, 1280x538 [SAR 1:1 DAR 640:269], q=-1--1, 3360 kb/s, 23.98 fps, 90k tbn, 23.98 tbc (default)
    Metadata:
      encoder         : Lavc58.54.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 3360000/0/3360000 buffer size: 6720000 vbv_delay: -1
    Stream #0:1: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp, 384 kb/s (default)
    Metadata:
      encoder         : Lavc58.54.100 libmp3lame
frame=   77 fps=0.0 q=9.0 size=N/A time=00:00:03.72 bitrate=N/A speed=7.44x    
frame=  217 fps=217 q=10.0 size=N/A time=00:00:09.36 bitrate=N/A speed=9.34x    
[hls @ 0x563227fce900] Opening '/transcode/6f1672a3fae3e09591d608543fa5a32c1.ts' for writing
frame=  355 fps=236 q=10.0 size=N/A time=00:00:15.04 bitrate=N/A speed=  10x    
frame=  485 fps=242 q=25.0 size=N/A time=00:00:20.59 bitrate=N/A speed=10.3x    
```
``
