### ISSUE TITLE
Lack of clarity in docker-compose instructions

### ISSUE THREAD

**Issue by gut5** [jellyfin/jellyfin-docs#373]
Instructions provided were unclear, could be more helpful especially since this is probably the simplest way for many people who want to run jellyfin on a home server. Lack of clarity especially around persistent volumes used for config and cache.
Also, removing the network mode host line made it connect where it wasn't doing so before. It was getting stuck on the ExecuteQueuedTasks part.
https://pastebin.com/raw/iyqf7wiU

Removing the network mode line finally got me into the interface.

I only got it working after setting up with the following docker-compose file (notice the commented-out network-mode line)

```
version: "3"
volumes:
  jellyfin-config:
  jellyfin-cache:
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    #network_mode: "host"
    volumes:
        - /home/guts/media:/media
       - jellyfin-cache:/cache
        - jellyfin-config:/config
    ports:
        - "127.0.0.1:8096:8096"

```
